-- MySQL Script generated by MySQL Workbench
-- qua 30 out 2024 14:06:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `idCliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome Cliente` VARCHAR(45) NULL,
  `Telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fornecedores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedores` (
  `Codigofornecedor` INT NOT NULL AUTO_INCREMENT,
  `Nome fornecedor` VARCHAR(45) NULL,
  `Telefone` VARCHAR(45) NULL,
  `Cidade` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigofornecedor`),
  UNIQUE INDEX `Codigofornecedor_UNIQUE` (`Codigofornecedor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Precos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Precos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Precos` (
  `Precos` INT NOT NULL,
  `Preco` FLOAT NULL,
  `Produtos_idProdutos` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Precos`),
  INDEX `fk_Precos_Produtos1_idx` (`Produtos_idProdutos` ASC) VISIBLE,
  CONSTRAINT `fk_Precos_Produtos1`
    FOREIGN KEY (`Produtos_idProdutos`)
    REFERENCES `mydb`.`Produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produtos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produtos` (
  `idProdutos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(45) NULL,
  `Marca` VARCHAR(45) NULL,
  `Unidade` VARCHAR(45) NULL,
  `Fornecedores_Codigofornecedor` INT NOT NULL,
  PRIMARY KEY (`idProdutos`),
  INDEX `fk_Produtos_Fornecedores_idx` (`Fornecedores_Codigofornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_Produtos_Fornecedores`
    FOREIGN KEY (`Fornecedores_Codigofornecedor`)
    REFERENCES `mydb`.`Fornecedores` (`Codigofornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Venda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Venda` (
  `idVenda` INT NOT NULL AUTO_INCREMENT,
  `quantidade` VARCHAR(45) NULL,
  `Produtos_idProdutos` INT UNSIGNED NOT NULL,
  `Clientes_idCliente` INT UNSIGNED NOT NULL,
  `Precos_Precos` INT NOT NULL,
  PRIMARY KEY (`idVenda`),
  INDEX `fk_Venda_Produtos1_idx` (`Produtos_idProdutos` ASC) VISIBLE,
  INDEX `fk_Venda_Clientes1_idx` (`Clientes_idCliente` ASC) VISIBLE,
  INDEX `fk_Venda_Precos1_idx` (`Precos_Precos` ASC) VISIBLE,
  CONSTRAINT `fk_Venda_Produtos1`
    FOREIGN KEY (`Produtos_idProdutos`)
    REFERENCES `mydb`.`Produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Clientes1`
    FOREIGN KEY (`Clientes_idCliente`)
    REFERENCES `mydb`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Precos1`
    FOREIGN KEY (`Precos_Precos`)
    REFERENCES `mydb`.`Precos` (`Precos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
