-- MySQL Script generated by MySQL Workbench
-- qua 30 out 2024 15:15:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `idCliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(45) NULL,
  `telefone_cliente` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fornecedores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedores` (
  `Codigofornecedor` INT NOT NULL AUTO_INCREMENT,
  `nome_fornecedor` VARCHAR(45) NULL,
  `telefone_fornecedor` VARCHAR(45) NULL,
  `cidade_fornecedor` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigofornecedor`),
  UNIQUE INDEX `Codigofornecedor_UNIQUE` (`Codigofornecedor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produtos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produtos` (
  `idProdutos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(45) NULL,
  `Marca` VARCHAR(45) NULL,
  `Unidade` VARCHAR(45) NULL,
  `Fornecedores_Codigofornecedor` INT NOT NULL,
  `VALOR` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idProdutos`),
  INDEX `fk_Produtos_Fornecedores_idx` (`Fornecedores_Codigofornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_Produtos_Fornecedores`
    FOREIGN KEY (`Fornecedores_Codigofornecedor`)
    REFERENCES `mydb`.`Fornecedores` (`Codigofornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Venda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Venda` (
  `idVenda` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `Clientes_idCliente` INT UNSIGNED NOT NULL,
  `Produtos_idProdutos1` INT UNSIGNED NOT NULL,
  `Custo` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idVenda`),
  INDEX `fk_Venda_Clientes1_idx` (`Clientes_idCliente` ASC) VISIBLE,
  INDEX `fk_Venda_Produtos2_idx` (`Produtos_idProdutos1` ASC) VISIBLE,
  CONSTRAINT `fk_Venda_Clientes1`
    FOREIGN KEY (`Clientes_idCliente`)
    REFERENCES `mydb`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Produtos2`
    FOREIGN KEY (`Produtos_idProdutos1`)
    REFERENCES `mydb`.`Produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb`;

DELIMITER $$

USE `mydb`$$
DROP TRIGGER IF EXISTS `mydb`.`Venda_BEFORE_INSERT` $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Venda_BEFORE_INSERT` BEFORE INSERT ON `Venda` FOR EACH ROW
BEGIN
  DECLARE product_price FLOAT;

  -- Obter o preço do produto
  SELECT VALOR INTO product_price FROM `mydb`.`Produtos` WHERE idProdutos = NEW.Produtos_idProdutos1;

  -- Calcular o custo
  SET NEW.Custo = NEW.quantidade * product_price;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
