-- MySQL Script generated by MySQL Workbench
-- ter 05 nov 2024 14:02:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`aluno` ;

CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `prontuario` INT NOT NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `prontuario_UNIQUE` (`prontuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno_curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`aluno_curso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`aluno_curso` (
  `aluno_id` INT UNSIGNED NOT NULL,
  `curso_id` INT UNSIGNED NOT NULL,
  `situacao` VARCHAR(45) NULL,
  `data_matricula` DATETIME NULL,
  PRIMARY KEY (`aluno_id`, `curso_id`),
  INDEX `fk_aluno_has_curso_curso1_idx` (`curso_id` ASC) VISIBLE,
  INDEX `fk_aluno_has_curso_aluno_idx` (`aluno_id` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_has_curso_aluno`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `mydb`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_curso_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `mydb`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno_disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`aluno_disciplina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`aluno_disciplina` (
  `aluno_id` INT UNSIGNED NOT NULL,
  `disciplina_id` INT UNSIGNED NOT NULL,
  `situacao` VARCHAR(45) NULL,
  PRIMARY KEY (`aluno_id`, `disciplina_id`),
  INDEX `fk_aluno_has_disciplina_disciplina1_idx` (`disciplina_id` ASC) VISIBLE,
  INDEX `fk_aluno_has_disciplina_aluno1_idx` (`aluno_id` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_has_disciplina_aluno1`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `mydb`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_disciplina_disciplina1`
    FOREIGN KEY (`disciplina_id`)
    REFERENCES `mydb`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno_turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`aluno_turma` ;

CREATE TABLE IF NOT EXISTS `mydb`.`aluno_turma` (
  `aluno_id` INT UNSIGNED NOT NULL,
  `turma_id` INT UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`aluno_id`, `turma_id`),
  INDEX `fk_aluno_has_turma_turma1_idx` (`turma_id` ASC) VISIBLE,
  INDEX `fk_aluno_has_turma_aluno1_idx` (`aluno_id` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_has_turma_aluno1`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `mydb`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_turma_turma1`
    FOREIGN KEY (`turma_id`)
    REFERENCES `mydb`.`turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`curso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(5) NOT NULL,
  `duracao` TINYINT UNSIGNED NOT NULL,
  `tipo+duracao` ENUM("semestre", "ano") NOT NULL,
  `data_inicio` DATE NULL,
  `periodo` ENUM("matutino", "verpertino", "noturno", "integral") NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`disciplina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`disciplina` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(5) NOT NULL,
  `semestre` TINYINT NULL,
  `aulas_semana` INT NULL,
  `aulas_totais` INT NULL,
  `area` VARCHAR(45) NULL,
  `curso_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_disciplina_curso1_idx` (`curso_id` ASC) VISIBLE,
  CONSTRAINT `fk_disciplina_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `mydb`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`professor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`professor` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `prontuario` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professor_turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`professor_turma` ;

CREATE TABLE IF NOT EXISTS `mydb`.`professor_turma` (
  `professor_id` INT UNSIGNED NOT NULL,
  `turma_id` INT UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`professor_id`, `turma_id`),
  INDEX `fk_professor_has_turma_turma1_idx` (`turma_id` ASC) VISIBLE,
  INDEX `fk_professor_has_turma_professor1_idx` (`professor_id` ASC) VISIBLE,
  CONSTRAINT `fk_professor_has_turma_professor1`
    FOREIGN KEY (`professor_id`)
    REFERENCES `mydb`.`professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_has_turma_turma1`
    FOREIGN KEY (`turma_id`)
    REFERENCES `mydb`.`turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sala` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sala` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `computadores` INT NULL,
  `projetor` TINYINT NULL,
  `lousa_digital` TINYINT NULL,
  `bloco` VARCHAR(45) NULL,
  `andar` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sala_turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sala_turma` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sala_turma` (
  `sala_id` INT UNSIGNED NOT NULL,
  `turma_id` INT UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`sala_id`, `turma_id`),
  INDEX `fk_sala_has_turma_turma1_idx` (`turma_id` ASC) VISIBLE,
  INDEX `fk_sala_has_turma_sala1_idx` (`sala_id` ASC) VISIBLE,
  CONSTRAINT `fk_sala_has_turma_sala1`
    FOREIGN KEY (`sala_id`)
    REFERENCES `mydb`.`sala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sala_has_turma_turma1`
    FOREIGN KEY (`turma_id`)
    REFERENCES `mydb`.`turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`turma` ;

CREATE TABLE IF NOT EXISTS `mydb`.`turma` (
  `id` INT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(2) NULL,
  `disciplina_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_turma_disciplina1_idx` (`disciplina_id` ASC) VISIBLE,
  CONSTRAINT `fk_turma_disciplina1`
    FOREIGN KEY (`disciplina_id`)
    REFERENCES `mydb`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
